### ISSUE TITLE
Nomenclature of key vars

### ISSUE THREAD

**Issue by bennyzen** [xlanex6/nuxt-meilisearch#12]
Maybe it's just me, but I'm somehow confused about the new names for the API keys (`readApiKey`, `writeApiKey`). 

When asking Meili for its actual keys, we'll get an answer like:
```
...
{
	...
	"description": "Default Search API Key (Use it to search from the frontend)",
	"key": "a1f03dd617bdf279da6fbcea48fe29e981f0d0165c6d534cc86a36437d3fc",
	...
},
{
	...
	"description": "Default Admin API Key (Use it for all other operations. Caution! Do not use it on a public frontend)",
	"key": "b915eac917a92d956a6458a92f572bcdf07b41d82c7532b82eca217dda83d",
	...
}
...
```
So, from my point of view the vars should adapt the naming scheme given by Meili itself (maybe `searchApiKey` and `adminApiKey`). Please correct me if I'm wrong. And yes, it's really just a detail.

**Comment by xlanex6** [comment]
fully agree 
i will change for this name 
naming convention is always complexe 

you're right, let's try to stick to meilisearch choice, keep it simple as we can.

**Comment by xlanex6** [comment]
@bennyzen 

Done I push a new release and update DOC site.

**Comment by bennyzen** [comment]
Awesome. While you're working on the docs, please make sure you find-and-replace all `Exemple -> Example` just to remove that minor typo. 

(Was just working on a quick PR, but my editor messed up your files and accidentally reformatted them. So I'll better leave the fix up to you with your settings.)

**Comment by xlanex6** [comment]
true typo, my bad , it's bue about ma native lang 🇫🇷, I'm french, and we write `exemple` and not `example` in `FR`
I will fix it 

thanks for spot this 🙏 🇫🇷
