### ISSUE TITLE
useMeilisearchClient is not defined

### ISSUE THREAD

**Issue by bennyzen** [xlanex6/nuxt-meilisearch#13]
The current version does not seem to work with Nuxt v3.0.0.

Here's a quick example/reproduction on StackBlitz:

https://stackblitz.com/edit/nuxt-starter-r2ikbg?file=app.vue

**Comment by xlanex6** [comment]
i update lib today 
it should be works 

can you try it and let me know 🙏

**Comment by bennyzen** [comment]
yes, it's fixed. works. 

thank you for the quick fix.
