### ISSUE TITLE
Hits always show me 200 results. The clientOptions didn´t work. 

### ISSUE THREAD

**Issue by hermesalvesbr** [xlanex6/nuxt-meilisearch#15]
Hi there, thanks for your module!

I made something wrong? I'm trying to limit the results for 5 "hits" for the all project. 

![image](https://user-images.githubusercontent.com/379850/203146170-d1bacf41-0199-496c-b843-3423b24af6c7.png)
```

RootDir: /home/hermes/Projetos/cloud/meilisearch/nuxt                 16:52:10
Nuxt project info:                                                    16:52:10

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`, `meilisearch`
- Runtime Modules:  `nuxt-meilisearch@0.1.6`
- Build Modules:    `-`
------------------------------
```

**Comment by xlanex6** [comment]
Hi @hermesalvesbr 

200 is higher than default config ( 50 )
https://github.com/xlanex6/nuxt-meilisearch/blob/da032b814d1ba8f36370ac60ad62f75829271732/src/module.ts#L46

I need to investigate on this 

I will do my best to fix it

**Comment by xlanex6** [comment]
@hermesalvesbr 
Can you give me the version of Meiliserch instance `v0.28`, `v0.29`...

thanks

**Comment by xlanex6** [comment]
@hermesalvesbr 

you should config hits per page into 
`      <ais-configure :hits-per-page.camel="5" /> `
inside  `ais-instant-search` component 

NOT inside `nuxt.config.ts`

let me know if it works 

Exemple: https://github.com/xlanex6/nuxt-meilisearch/blob/da032b814d1ba8f36370ac60ad62f75829271732/playground/app.vue#L9

**Comment by hermesalvesbr** [comment]
Ok, by configure works. But placeholder no.
