### ISSUE TITLE
Sorting with the module

### ISSUE THREAD

**Issue by airv-b** [xlanex6/nuxt-meilisearch#16]
Hi there,

When I make curl queries (or directly in the browser via params in the url ex: "localhost:7700/indexes/recettes/search/?sort=last_update:desc"), I manage to use sorting.
However, using this module, I can't seem to find in the documentation how to do it.

Thank for your help.

nuxt3 : 3.0.0
meilisearch : 0.29.2
nuxt-meilisearch : 0.1.6

Best Regards,
Hervé

**Comment by airv-b** [comment]
I found a solution by updating my ranking rules.
https://docs.meilisearch.com/reference/api/settings.html#update-ranking-rules

`
curl \
  -X PUT 'http://localhost:7700/indexes/recettes/settings/ranking-rules' \
  -H 'Content-Type: application/json' \
  --data-binary '[
    "exactness",
    "words",
    "last_update:desc",
    "sort",
    "typo"
  ]'`

I don't know if there was a solution via the module, but it could be interesting to "override"

**Comment by xlanex6** [comment]
hey hervé 

it look's like a Meilisearch config. 

what about nuxt-meilisearch module  expérience ? 
doc is clear enough ? 

curious about DX feedback
