### ISSUE TITLE
Could not find a declaration file for module 'vue-instantsearch/vue3/es'

### ISSUE THREAD

**Issue by buluw** [xlanex6/nuxt-meilisearch#17]
Hi there, thanks for your module!

How to solve this error message：
Could not find a declaration file for module 'vue-instantsearch/vue3/es'. 
'D:/code/nuxt/test/testb/node_modules/.pnpm/vue-instantsearch@4.6.0/node_modules/vue-instantsearch/vue3/es/index.js' 
implicitly has an 'any' type.ts(7016)

meilisearch in demo could run, but has this error message

![vue-instantsearch](https://user-images.githubusercontent.com/45087912/209102586-8ef34d33-3229-484e-b86e-4750fee710e1.png)

nuxt3 : 3.0.0
nuxt-meilisearch : 0.1.7
meilisearch : 0.30.2

**Comment by xlanex6** [comment]
Hi @buluw 

your request is like to Vue-Instantsearch itself 
But 

I find this gist , could be helpful 
maybe nor fully updated

https://gist.github.com/Tocas97/6b058a60108b67cc0109abbf3cef0fb3

Let me knows if it helps

**Comment by buluw** [comment]
thanks for reply
where should I place it?

**Comment by buluw** [comment]
I place the file `[vue-instantsearch.d.ts](https://gist.github.com/Tocas97/6b058a60108b67cc0109abbf3cef0fb3#file-vue-instantsearch-d-ts)` to ./types 
and change `declare module "vue-instantsearch" {...}` to `declare module "vue-instantsearch/vue3/es" {...}`
it's no more error message, everything works fine for now

**Comment by buluw** [comment]
I found an easier way to use vue instanse components:

create `vue-instantsearch.js` into ./plugins

```javascript
import InstantSearch from 'vue-instantsearch/vue3/es';
import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.use(InstantSearch)
})
```
no more need use import in components
