### ISSUE TITLE
meiliesearch options in defineNuxtConfig should be 'options' and not 'clientOptions' as mentioned in the Frontend docs.

### ISSUE THREAD

**Issue by matiyin** [xlanex6/nuxt-meilisearch#19]
In the Frontend docs this is described as setup:

`meilisearch: {  
  clientOptions: {... } 
}`

But those options didn't work for me. Looking at `/node_modules/nuxt-meilisearch/dist/runtime/composables/useMeilisearchClient.mjs` is noticed that you have to use `options` instead of `clientOptions`:

`const { meilisearchClient: { hostUrl, searchApiKey, options } } = useRuntimeConfig().public;`

The options work now, I changed the setup to:

`meilisearch: {  options: { ... } }`

**Comment by xlanex6** [comment]
I moved to your point 

It will be live on next release
