### ISSUE TITLE
how to programatically trigger or filter a search via a custom function

### ISSUE THREAD

**Issue by matiyin** [xlanex6/nuxt-meilisearch#20]
How can I do a custom search from a method in a vue component, instead of only using the widgets within <ais-instant-search>?

When I do this:

``` 
const search = useMeilisearchClient()
search.search('test')
```
I get the js error: `searchRequest.indexName is undefined`

I can't seem to find how to set the index via this method.

How would one do this in Nuxt Meilisearch?:
```
const client = algoliasearch('YourApplicationID', 'YourSearchOnlyAPIKey');
const index = client.initIndex('contacts');

// Search for "query string" in the index "contacts"
index.search('query string').then(({ hits }) => {
  console.log(hits);
});
```

**Comment by xlanex6** [comment]
Hi @matiyin 
Thanks for your questions 

two options for you: 

1 - you want to use Algolia Vue 3 component lib , so stick to docs 
https://nuxt-meilisearch-docs.netlify.app/setting/frontend

2 - you want to do it as `raw` , without Algolia lib 
So in nuxt , you can use `useFetch` to server url 
OR
use JS client 
as explain here https://docs.meilisearch.com/reference/api/search.html#example


EDIT
keep it mind , it always ask index name first
```vue
const client = useMeilisearchClient()
client.index('movies').search('American ninja')
```

**Comment by xlanex6** [comment]
HI @matiyin 

is it right for you or you need some help ?
