### ISSUE TITLE
scopable configuration

### ISSUE THREAD

**Issue by geoHeil** [xlanex6/nuxt-meilisearch#26]
How can I scope the default configuration of https://github.com/xlanex6/nuxt-meilisearch/blob/0aaa22ce5fa1569d2e36960eaf3a4a329fe920fc/src/module.ts#L29 meilisearch and move it inside the runtimeConfig? https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables

The reason is: only there the ENV-based substitution NUXT_API_SECRET works for keys.
The keys which are rendered here are hard-set into the JS scripts. Even for secrets. And it would be bad practice to leak the secrets (if the bundled application using nuxt-meilisearch) is put in a docker container which is stored on some artifact store

**Comment by xlanex6** [comment]
@geoHeil 
I scared that I could not move this `configKey` into runtimeConfig 
It's critical
Have you try to fork and make it works ? 

EDIT: Sorry for late response 😔

**Comment by geoHeil** [comment]
I tried this: https://github.com/nuxt/nuxt/discussions/20584 but unfortunately, could not yet get it to work. Unfortunately, I am not really a frontend expert, so I am a bit hesitant in forking a JS project.

**Comment by xlanex6** [comment]
have you try simply `process.env.MEILISEARCH_URL`
in you `.env` file
MEILISEARCH_URL=https://myMeilisearchServer.com 

it will be in public config anyway  
set Env like so 
https://nuxt.com/docs/guide/going-further/runtime-config#exposing-runtime-config

**Comment by geoHeil** [comment]
What would be the possibilities for loading the search and admin API key? I am not really worried about the DNS being hardcoded.

**Comment by xlanex6** [comment]
@geoHeil 
do you find a solution ?

**Comment by geoHeil** [comment]
so far not / continued to use it as -is for now
