### ISSUE TITLE
client.index is not a function

### ISSUE THREAD

**Issue by Aft1n** [xlanex6/nuxt-meilisearch#29]
Hello, i am trying to make the search work inside the script tag, but it gives me an error 
"500 client.index is not a function"    

Meilisearch works with instantsearch plugin, but not in script tag. i use Nuxt v3.6.1

am I doing something wrong or is there an issue?

**Comment by xlanex6** [comment]
hi 
can you share your comp. code ?
please 

i will help me to dig to jt
