### ISSUE TITLE
Documentation not found https://nuxt-meilisearch-docs.netlify.app/

### ISSUE THREAD

**Issue by hermesalvesbr** [xlanex6/nuxt-meilisearch#40]
Hi there,

I'm here beacuse i have errors of types with typescript:

![Captura de tela de 2023-08-22 10-44-21](https://github.com/xlanex6/nuxt-meilisearch/assets/379850/7cdced5f-0d91-4a36-b0a8-c194cb6383dc)

> Support for Vue [Algolia Vue 3 InstantSearch](https://github.com/algolia/vue-instantsearch) components (optional)

I need to specify some to types work's with your module?  Because if I don't call vue-instantsearch/vue3/es the components, like "ais-instant-search " don't work. And neither do the types, they keep giving errors. Do you have any examples with <script setup lang="ts"> ?

 ```
 meilisearch: {
      hostUrl: process.env.NUXT_MEILI_HOST_URL,
      searchApiKey: process.env.NUXT_MEILI_API_SECRET,
      adminApiKey: process.env.NUXT_MEILI_API_SECRET,
      serverSideUsage: true,
      clientOptions: {
        placeholderSearch: true,
        paginationTotalHits: 5, 
        finitePagination: true, 
        primaryKey: 'primaryKey', 
        keepZeroFacets: false 
      },
      instantSearch: {
        theme: 'satellite'
      }
    },
```

**Comment by xlanex6** [comment]
hi 

i'm working on typed all module. 
stay tuned 
it's coming

**Comment by xlanex6** [comment]
Hi @hermesalvesbr 

 [new doc site ](nuxt-meilisearch.vercel.app)
