### ISSUE TITLE
Meili below v0.27 does not support `highlightPreTag`

### ISSUE THREAD

**Issue by bennyzen** [xlanex6/nuxt-meilisearch#6]
MeiliSearch below version 0.27 does not seem to understand or support the `highlightPreTag`. The error I got is something like:
```json
{
    "message": "Json deserialize error: unknown field `highlightPreTag`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `matches`, `filter`, `sort`, `facetsDistribution` at line 1 column 55",
    "code": "bad_request",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#bad_request"
}
```
Maybe this could be added to the docs to save some headaches.

**Comment by xlanex6** [comment]
Here a real problem with different version ( meilisearch and meilisearchClient  )

If mismatch , it could have some problem like you mention. 

Are  you free for a pull request ?

**Comment by xlanex6** [comment]
After config `highlightPreTag` on Meilisearch .it works
