### ISSUE TITLE
"ais-refinement-list" not showing anything

### ISSUE THREAD

**Issue by nuwanz** [xlanex6/nuxt-meilisearch#7]
Hello there, 

Thanks for the awesome plugin. 
I have a problem when I use "ais-refinement-list" 
It doesn't show anything. Even after importing the module.

```
import {
    AisInstantSearch,
    AisConfigure,
    AisHits,
    AisSearchBox,
    AisRefinementList,
  } from 'vue-instantsearch/vue3/es';
```
 Thanks.
Nuwan T.

**Comment by xlanex6** [comment]
Hi @nuwanz 

On paper `AisRefinementList` works based on https://github.com/meilisearch/instant-meilisearch#table-of-widgets but not at 100%, some function or not support.
Is there your case ?

how do you implement in your template ? can you share the way you implement ?
Which version of Meilisearch do you use?

**Comment by nuwanz** [comment]
Hi xlanex6, 

Thanks for the quick reply.

front end code 
`<ais-refinement-list attribute="Category"></ais-refinement-list>`

When I run the application. Get this error from the browser.
**"Error: MeiliSearchApiError: Invalid facet distribution, the fields `Category, Title` are not set as filterable."**

Thanks,
Nuwan T.

**Comment by xlanex6** [comment]
Hi @nuwanz 
it's look a `MeiliSearchApiError`, Are you well set `Category, Title` in your meilliseach  config 
you can do so like this 
https://docs.meilisearch.com/learn/advanced/filtering_and_faceted_search.html#configuring-filters

keep me update

**Comment by xlanex6** [comment]
@nuwanz 
After update your  filterable-attributes with ( in your case `Category ` ) 

It should works.

![CleanShot 2022-10-12 at 12 53 28](https://user-images.githubusercontent.com/13418668/195324584-83054a4a-7f5d-498b-b1dc-965123d92dcc.png)
