### ISSUE TITLE
Module breaks in Nuxt rc8

### ISSUE THREAD

**Issue by bennyzen** [xlanex6/nuxt-meilisearch#8]
Using this module with Nuxt rc8, I get this error on the client-side:
`hogan.js does not provide an export named 'default'`

**Comment by xlanex6** [comment]
Hi @bennyzen 

Yes, I notice same issues during my update. 
Not fixed yet 

I'm still on it

**Comment by bennyzen** [comment]
I've tried to fix it on my own using an alias directive in `nuxt.config.ts`, but I miserably failed at it. So I'll gladly wait for your fix.

**Comment by nuwanz** [comment]
Got the same issue. Waiting for the fix.

**Comment by nuwanz** [comment]
@bennyzen @xlanex6  Any fix for this issue?

**Comment by xlanex6** [comment]
@bennyzen 
@nuwanz 

It's relative to Vue Instant search 
I still dig on it 
https://github.com/algolia/vue-instantsearch/issues/1098
https://github.com/Haroenv/nuxt3-vue-instansearch-example/blob/main/search.vue#L26-L61

Make sure I do my best to solve this.

**Comment by xlanex6** [comment]
@nuwanz 

You can transpile `vue-instantsearch` to fix 

```js
nuxt.config.ts
...
  meilisearch: {
    hostUrl: 'http://0.0.0.0:7700',
    apiKey: 'xxx',
    instantSearch: false
  },
  build: {
    transpile: ['vue-instantsearch']
  }
  ...
```

and in your comp. 

```vue
import {
    AisInstantSearch,
    AisConfigure,
    AisHits,
    AisSearchBox,
    AisRefinementList,
  } from 'vue-instantsearch/vue3/es';
```

not very clean but it's a quick fix until I clean it with native apply to the module ( if I could )

**Comment by nuwanz** [comment]
@xlanex6 Thanks. I will check that fix on my project. 
Keep up the awesome work.

**Comment by xlanex6** [comment]
I fix on https://github.com/xlanex6/nuxt-meilisearch/releases/tag/v0.1.3

**Comment by nuwanz** [comment]
Thanks man.. I will check it.
