### ISSUE TITLE
Using GeoPoint feature with nuxt-meilisearch and vue-instantsearch

### ISSUE THREAD

**Issue by fkaaziebu** [xlanex6/nuxt-meilisearch#83]
Can't pass `sort` search parameter along with `gePoint` of meilisearch when using the `useInstantSearch()` composable along with `vue-instantsearch` ui components

**Comment by xlanex6** [comment]
Hi @fkaaziebu 
Can share some code to verify if it's Algolia Comp / Meilisearch / module issue, it will help me a lot . 

thanks
