### ISSUE TITLE
Cannot use VueInstantSearch components with pnpm

### ISSUE THREAD

**Issue by Strift** [xlanex6/nuxt-meilisearch#96]
Hi @xlanex6 👋 

I made a simple [example component](https://stackblitz.com/edit/nuxt-starter-wryntj?file=app.vue) using the module and ran into an error: it's not possible to use InstantSearch components when installing dependencies with `pnpm install`.

If we want the VueInstantSearch components to be available, we need to install the dependencies with `pnpm install --shamefully-hoist`

I don't know if this can be fixed? In the meantime, we might want to update the docs to explain this caveat.

Cheers!

**Comment by xlanex6** [comment]
hi @Strift 

You right. i should notice this into the doc for `pnpm` user. 

But maybe, nuxt already fix it by default.

**Comment by xlanex6** [comment]
this is not a problem anymore, thanks to magic cli command

```bash
npx nuxi@latest module add nuxt-meilisearch
```
